// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiddleMaker.Data;

#nullable disable

namespace RiddleMaker.Data.Migrations
{
    [DbContext(typeof(RiddleMakerContext))]
    [Migration("20230403160706_ChangeRiddleMaxLength_02")]
    partial class ChangeRiddleMaxLength_02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RiddleMaker.Data.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("nvarchar(31)");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("RiddleMaker.Data.Models.Riddle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(217)
                        .HasColumnType("nvarchar(217)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.ToTable("Riddles");
                });

            modelBuilder.Entity("RiddleMaker.Data.Models.Riddle", b =>
                {
                    b.HasOne("RiddleMaker.Data.Models.Answer", "Answer")
                        .WithMany("Riddles")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("RiddleMaker.Data.Models.Answer", b =>
                {
                    b.Navigation("Riddles");
                });
#pragma warning restore 612, 618
        }
    }
}
